### ISSUE TITLE
Version 1.0.0 and 1.1.0 beta2 doesn't work.

### ISSUE THREAD

**Issue by Jepl4r** [isXander/Controlify#43]
Added the mod to my Minecraft instance, opened it, Minecraft started loading and at half the progress bar it crashed. Tried without other mods and it crashed too.

 - OS: [MacOS 13.3]
 - Minecraft Version: [1.19.4]
 - Mod Version: [1.1.0 beta 2 1.19.4]

I'm on Mac and it doesn't work. It's not that, I tried on my "old" Windows PC and it behaved the same.

As for version 1.0.0 of the mod it loads fine but I can't use the controller or change the settings of the mod. The controller I'm using is a Xbox Series Controller.

**Comment by isXander** [comment]
Can you please post latest.log after repeating this?

**Comment by Jepl4r** [comment]
> Can you please post latest.log after repeating this?

This is with the mods I have enabled
[latest.log](https://github.com/isXander/Controlify/files/11211155/latest.log)

**Comment by Jepl4r** [comment]
And this is with only controlify and fabric api
[latest.log](https://github.com/isXander/Controlify/files/11211166/latest.log)

**Comment by Jepl4r** [comment]
The version I used is 1.1.0 beta 2

**Comment by isXander** [comment]
Ah, the problem is something to do with MacOS. I will look into it.

**Comment by isXander** [comment]
Two issues here: HIDAPI is failing to load, which identifies controllers, and Fabric Screen API is also failing, something to do with its event system.

**Comment by Jepl4r** [comment]
So it’s a bug with your mod or MacOS? Cause midnightcontrol works fine.

**Comment by isXander** [comment]
Bug with my mod DUE to it being loaded on macOS. It uses native libraries that are failing to load on your OS.

**Comment by isXander** [comment]
Same problem.

**Comment by Jepl4r** [comment]
Why did you close the issue? Is it resolved?

**Comment by isXander** [comment]
The crash is solved.

**Comment by Jepl4r** [comment]
Still crashes :(
[latest.log](https://github.com/isXander/Controlify/files/11301584/latest.log)
