### ISSUE TITLE
[Bug] Player's head disappears with repeated log errors "[Render thread/ERROR]: Invalid entity rotation: NaN, discarding."

### ISSUE THREAD

**Issue by MartyX98** [isXander/Controlify#526]
### Current Behaviour

The player's head disappears when I control the game using a controller. When I start using keyboard and mouse, the problem disappears, but returns back the moment I start using controller again. Alongside it, repeated error messages in game's log appear.

### Expected Behaviour

To not have this bug happen.

### Using controller;
![Image](https://github.com/user-attachments/assets/62050355-5c7f-4508-8e84-9c0eb953f867)
### Using keyboard;
![Image](https://github.com/user-attachments/assets/81f67744-a090-4c6d-96f7-d464e6bf17f6)
### Logs from Modrinth App
![Image](https://github.com/user-attachments/assets/7c174d8f-9a85-434e-9774-71fff234676d)

### Reproduction Steps

**Environment**
- OS: Windows 11 Home (24H2)
- Controller: PS5 DualSense controller, connected via USB.
- Minecraft 1.21.4 (Fabric) through Modrinth app with mods; 
  - Controlify (2.0.2+1.21.4-fabric) 
  - Fabric API (0.115.1+1.21.4)
  - YetAnotherConfigLib (3.6.2+1.21.4-fabric)

### Logs

```shell
...
[02:38:45] [Render thread/ERROR]: Invalid entity rotation: NaN, discarding.
[02:38:45] [Render thread/ERROR]: Invalid entity rotation: NaN, discarding.
[02:38:45] [Render thread/ERROR]: Invalid entity rotation: NaN, discarding.
[02:38:45] [Render thread/ERROR]: Invalid entity rotation: NaN, discarding.
[02:38:45] [Render thread/ERROR]: Invalid entity rotation: NaN, discarding.
...
```

### Mod Version

Controlify (2.0.2+1.21.4-fabric)

### Controller

PS5 DualSense Controller

### Bluetooth

- [ ] Yes

### Operating System

Windows

### ARM

- [ ] Yes

### Just to make sure...

- [x] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [x] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by hecktexk** [comment]
the same thing is happening to me

**Comment by DoggoNako** [comment]
Same issue here:

This only happens with a controller, at first I thought it was my Java installation but GraalVM and OpenJDK install give the same issue.

- PrismLauncher
- Windows 11 & Arch Linux 6.13.1
- Xbox One Controller via bluetooth
- Minecraft 1.20.1 w/ Fabric 0.16.10
  - Controlify v2.0.2+1.20.1-fabric
  - Fabric API 0.92.3+1.20.1
  - YetAnotherConfigLib 3.6.2+1.20.1-fabric

[logs here](https://mclo.gs/LTDRTlM)

Without moving camera:
![Image](https://github.com/user-attachments/assets/71579c09-5954-4ac1-a937-db410283dcd4)

Breaking Blocks without moving camera:
![Image](https://github.com/user-attachments/assets/8f40d687-16fb-4c1b-8084-1d858c7dff56)

Also in video:
https://youtu.be/Kf1uftDOnO0

Hope it helps !

**Comment by DoggoNako** [comment]
*A friend of mine doesn't have this issue with Forge, I'll try to reproduce on other modloader than Fabric*

**Comment by apple8404** [comment]
[latest.log](https://github.com/user-attachments/files/18683215/latest.log)

more logs for the log gods. same issue, win11, minecraft 1.21.4, xbox core controller via bluetooth

**Comment by xXANTIHERO259Xx** [comment]
Just came back to the game after a 4 month break and it started happening, if possible i might downgrade to an earlier version and see if the bug is still happening

**Comment by xXANTIHERO259Xx** [comment]
alright i downgraded to 2.0.0+1.21 and the bug isn't there if your controller is supported on that version and it fits the mod pack you're creating/playin then play on that instead

**Comment by DoggoNako** [comment]
For me, downgrading to 2.0.1+1.20.1 and I don't have this issue

**Comment by Greenknight9000** [comment]
Glad to see I'm not the only one suffering with this issue. It's happening on Fabric 1.21.1 using the latest version of the mod
![Image](https://github.com/user-attachments/assets/1e22c5bd-6399-43c3-97b7-4e77385b96c1)

**Comment by DrSex420** [comment]
> alright i downgraded to 2.0.0+1.21 and the bug isn't there if your controller is supported on that version and it fits the mod pack you're creating/playin then play on that instead

Can confirm, 1.21.4 Steam Deck OLED, downgrading to 2.0.1 got rid of the log flood

**Comment by EssGeeEich** [comment]
This bug is solved in the very last version of Controlify.

While such version is not available on the various mod stores, you can download an updated build that's automatically generated from the Github CI here:

https://github.com/isXander/Controlify/actions/runs/13444067998/job/37565214600

On the left side, select your Minecraft version, open the "Run actions/upload-artifact" task and you'll find a download link there with the very last changes.

**Comment by nonbinary** [comment]
I'm playing on fabric, minecraft version 1.21.7, and this issue is still here. So I'm guessing it's reappeared?
